INSERT INTO quizzes (user_id, title, unique_id) VALUES (1, 'Introduction to Python', '0W2MZp');
INSERT INTO quizzes (user_id, title, unique_id) VALUES (2, 'History Trivia Challenge', 'OkkrBm');
INSERT INTO quizzes (user_id, title, unique_id) VALUES (3, 'Mathematics Quiz: Algebra Basics', 'S9Lw46');
INSERT INTO quizzes (user_id, title, unique_id) VALUES (1, 'Geography Quiz: World Capitals', 'wOOypZ');
INSERT INTO quizzes (user_id, title, unique_id) VALUES (2, 'Literature Quiz: Famous Authors', 'V5kVAH');
INSERT INTO quizzes (user_id, title, unique_id) VALUES (3, 'Science Quiz: Biology Fundamentals', 'bjjVj1');
INSERT INTO quizzes (user_id, title, unique_id) VALUES (1, 'Movie Buff Trivia', 'ZO1uQb');
INSERT INTO quizzes (user_id, title, unique_id) VALUES (2, 'Music Knowledge Quiz', 'UGtwDZ');
INSERT INTO quizzes (user_id, title, unique_id) VALUES (3, 'Art History Quiz: Renaissance Era', '85lomW');
INSERT INTO quizzes (user_id, title, unique_id) VALUES (1, 'Sports Trivia Challenge', 'nUF079');
INSERT INTO quizzes (user_id, title, unique_id) VALUES (2, 'Culinary Quiz: Cooking Techniques', 'tfqgjk');
INSERT INTO quizzes (user_id, title, unique_id) VALUES (3, 'Technology Quiz: Gadgets and Gizmos', 'nFZQsx');
